export const GET_PEOPLE_REQUESTED = 'GET_PEOPLE_REQUESTED';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';

export const GET_PLANET_LIST_REQUESTED = 'GET_PLANET_LIST_REQUESTED';
export const GET_PLANET_LIST_SUCCESS = 'GET_PLANET_LIST_SUCCESS';
export const GET_PLANET_LIST_FAILURE = 'GET_PLANET_LIST_FAILURE';

export const GET_PLANET_DETAILS_REQUESTED = 'GET_PLANET_DETAILS_REQUESTED';

export const AUTH_CHECK = 'AUTH_CHECK';

export const SIGN_OUT = 'SIGN_OUT';
