export const GET_SEARCH_AIRPORT = 'GET_SEARCH_AIRPORT';
export const GET_FLIGHT_SUCCESS = 'GET_FLIGHT_SUCCESS';
export const GET_FLIGHT_FAILURE = 'GET_FLIGHT_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const DEPARTURE_SEARCH_RESULT = 'DEPARTURE_SEARCH_RESULT';
export const RETURN_SEARCH_RESULT = 'RETURN_SEARCH_RESULT';